os: linux
dist: focal
language: python

<<<<<<< HEAD
<<<<<<< HEAD
# the new trusty images of Travis cause build errors with psycopg2, see https://github.com/travis-ci/travis-ci/issues/8897
dist: trusty
group: deprecated-2017Q4

python:
    - "2.7"
env:
<<<<<<< HEAD
<<<<<<< HEAD
    - PGVERSION=9.1 CKAN_BRANCH=master
    - PGVERSION=9.1 CKAN_BRANCH=release-v2.3-latest
    - PGVERSION=9.1 CKAN_BRANCH=release-v2.4-latest
    - PGVERSION=9.1 CKAN_BRANCH=release-v2.5-latest
    - PGVERSION=9.1 CKAN_BRANCH=release-v2.6-latest
=======
    - CKAN_BRANCH=master
    - CKAN_BRANCH=release-v2.3-latest
    - CKAN_BRANCH=release-v2.4-latest
    - CKAN_BRANCH=release-v2.5-latest
>>>>>>> 67cb935 (fix travis build)
=======
    - CKANVERSION=master
    - CKANVERSION=2.8
    - CKANVERSION=2.7
    - CKANVERSION=2.6
    - CKANVERSION=2.5
    - CKANVERSION=2.4
    - CKANVERSION=2.3
>>>>>>> 2cc3e65 (run test against multiple CKAN versions)
=======
>>>>>>> 84fb9e8 (pytest)
install:
    - bash bin/travis-build.bash
=======
>>>>>>> f4e5e0f (Fix travis config)
services:
    - redis
    - postgresql
    - docker

install: bash bin/travis-build.bash
script: bash bin/travis-run.bash

before_install:
    - pip install codecov
after_success:
    - codecov

jobs:
  include:
    - stage: Flake8
      python: 2.7
      env: FLAKE8=True
      install:
        - pip install flake8==3.5.0
        - pip install pycodestyle==2.3.0
      script:
        - flake8 --version
        # stop the build if there are Python syntax errors or undefined names
        - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude ckan
        # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
        # - flake8 . --count --max-line-length=127 --statistics --exclude ckan --exit-zero

    - python: "3.6"
      env: CKANVERSION=master
      services:
          - postgresql
          - redis
          - docker

    - python: "3.6"
      env: CKANVERSION="2.9"
      services:
          - postgresql
          - redis
          - docker

    - stage: Tests
      python: "2.7"
      env: CKANVERSION=master
      services:
          - postgresql
          - redis
          - docker

    - python: "2.7"
      env: CKANVERSION=2.8

    - python: "2.7"
      env: CKANVERSION=2.7

    - python: "2.7"
      env: CKANVERSION=2.6

cache:
  directories:
    - $HOME/.cache/pip
